server:
  servlet:
    path: /
    session:
        timeout: 1800
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:static/dist/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
      open-in-view: true
      properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL55Dialect
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings: true